# Secrets Manager — stores the RDS master credentials
#
# The password is generated by Terraform (random_password) so it never
# appears in code or in git. The RDS module reads it from this secret.


# 1. The secret container
#    recovery_window_in_days = 7 lets you restore the secret if accidentally deleted
resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "rds-db-credentials"
  description             = "Master credentials for the RDS PostgreSQL instance"
  recovery_window_in_days = 7

  tags = {
    Name        = "rds-db-credentials"
    Environment = var.environment
  }
}


# 2. A random password — generated once, stored in the secret
resource "random_password" "db" {
  length  = 32
  special = false # avoid characters PostgreSQL clients sometimes mis-handle
}


# 3. The actual secret content (username + password) as JSON
resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = "postgres"
    password = random_password.db.result
  })
}
